server:
  grpc_port: 30002
  http_port: 30003
database:
  host: 127.0.0.1
  port: 3306
  username: user
  password: 1234
  dbname: link_dev
  options: charset=utf8&parseTime=True&loc=Local
  migrate_file_path: "./infrastructure/migrations/"
service_info: # 要更改服务名的话,需要一同更改公共配置中的服务名
  name: shortlink_service
  version: 1.0.0
  desc: shortlink_service