server:
  port: 30002
database:
  host: 127.0.0.1
  port: 3306
  username: user
  password: 1234
  dbname: link_dev
  options: charset=utf8&parseTime=True&loc=Local
  migrate_file_path: "./infrastructure/migrations/"