version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=dev
    ports:
      - "3306:3306"
