services:
  mysql-dev:
    image: mysql:8
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./dbinit/dev/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
  redis-dev:
    image: redis:8
    restart: on-failure
    ports:
      - "6379:6379"
  rabbitmq-dev:
    image: rabbitmq:4-management
    restart: on-failure
    ports:
      - "5672:5672"
      -  "15672:15672"
  jaeger-dev:
    image: jaegertracing/jaeger
    restart: on-failure
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
  clickhouse-dev:
    image: clickhouse:latest
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./dbinit/dev/clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=1234

    