services:
  mysql-dev:
    image: mysql:8
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./dbinit/dev/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
  redis-dev:
    image: redis:8
    restart: on-failure
    ports:
      - "6379:6379"
  jaeger-dev:
    image: jaegertracing/jaeger
    restart: on-failure
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
  clickhouse-dev:
    image: clickhouse:latest
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./dbinit/dev/clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=1234
  kafka-dev:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    restart: on-failure
    environment:
      # --- 关键 KRaft 配置 ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller # 一体化模式
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      # 客户端（宿主机）通过 localhost:9092 连接
      # 内部服务（kafka-ui）通过 kafka:9092 连接
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Controller 仲裁配置 (单节点)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      # --- 其他开发配置 ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3


    