server:
  port: 20001
database:
  username: user
  password: 1234
  host: 127.0.0.1
  port: 3306
  dbname: tenant_dev
  options: charset=utf8&parseTime=True&loc=Local
  migration_file_path: "./migrations/"
service_info:
  name: tenant_service
  version: 1.0.0