api-gateway:
  port: 8080
  server-crt-file-path: ./config/certs/server.crt
  server-key-file-path: ./config/certs/server.key
service-info:
  name: api-gateway
  version: 1.0.0
  desc: api-gateway
global-rate-limiter:
  rate: -1.0
  capacity: 100
local-rate-limiter:
  rate: 10
  capacity: 50